Changes to verify if given entity exists in Nuage VM table
nuagenetworks/libvrsdk pull request #3
Opened 2016-10-11 15:55 UTC by rparulek

Changes to verify if given entity exists in Nuage VM table

2016-10-11 16:25 UTC, vishpat requested changes

2016-10-11 16:25 UTC, vishpat commented on api/Entity.go
> +        return false, fmt.Errorf("Unable to verify if entity exists in OVSDB %v", err)
Change error string to "OVSDB read error"

2016-10-11 16:25 UTC, vishpat commented on api/Entity.go
> +    if uuid == uuids[0] {
Do you need to check the count of uuids before this check?

2016-10-11 16:25 UTC, vishpat commented on api/Entity.go
> +    return true, nil
Shouldn't this return false?

2016-10-11 16:25 UTC, vishpat commented on api/Entity.go
> +func (vrsConnection *VRSConnection) CheckEntity(uuid string) (bool, error) {
Change function name to EntityExists

2016-10-11 18:59 UTC, rparulek commented on api/Entity.go
> +    	for _, uuid := range uuidRows {
Before this step; I will need to add a check for "nil" value of uuidRows interface above to handle the case wherein there is no UUID entry in VM Table

2016-10-12 15:07 UTC, abhat commented on api/Entity.go
> +    	for _, uuid := range uuidRows {
I understand go's scoping rules will hide the uuid declared in the for loop iteration from that passed to the function as argument. But for readability purposes, I would encourage you to rename the variable in the loop iteration to something else.

2016-10-12 15:07 UTC, abhat commented on api/NuageAPI_test.go
> +        	t.Fatalf("VM %s with UUID %s doesnot exist in OVSDB", vmInfo["name"], vmInfo["vmuuid"])
`does not` vs. `doesnot`

2016-10-12 15:07 UTC, abhat commented on api/Entity.go
> +    	if len(uuids) > 0 && uuid == uuids[0] {
If we expect uuids to be unique, is there a need for allowing `len(uuids) > 0`

2016-10-12 15:11 UTC, rparulek commented on api/Entity.go
> +    	if len(uuids) > 0 && uuid == uuids[0] {
I have a check for length to handle the scenario wherein no such UUID exists in OVSDB (for new entity) then "uuids" will be blank and program will panic trying to access uuids[0]

2016-10-13 14:42 UTC, vishpat approved these changes

2016-10-13 14:54 UTC, abhat commented on api/Entity.go
> +    	if len(uuids) > 0 && uuid == uuids[0] {
I meant you can always make sure that the `len(uuids) == 1`

2016-10-14 18:10 UTC, abhat commented on api/NuageAPI_test.go
> +        	t.Logf("VM %s with UUID %s exists in OVSDB", vmInfo["name"], vmInfo["vmuuid"])
`Entity %s with ID %s`

2016-10-14 18:10 UTC, abhat commented on api/NuageAPI_test.go
> +        	t.Fatalf("VM %s with UUID %s does not exist in OVSDB", vmInfo["name"], vmInfo["vmuuid"])
same as above line 321

2016-10-15 00:30 UTC, rparulek commented on api/NuageAPI_test.go
> +        	t.Logf("VM %s with UUID %s exists in OVSDB", vmInfo["name"], vmInfo["vmuuid"])
In this testcase; we are specifically creating a VM entity; so I think we are being more specific by stating "VM" and UUID instead of entity/id in the logs

2016-10-15 00:30 UTC, rparulek commented on api/NuageAPI_test.go
> +        	t.Fatalf("VM %s with UUID %s does not exist in OVSDB", vmInfo["name"], vmInfo["vmuuid"])
same as above

2016-10-19 13:53 UTC, merged